import { useState } from 'react';

const money = (value) => `KSh ${value.toLocaleString('en-KE')}`;

export default function CheckoutPanel({ cart, subtotal, onClose, onComplete }) {
  const [payment, setPayment] = useState('mpesa');
  const [complete, setComplete] = useState(false);
  const delivery = subtotal >= 5000 || subtotal === 0 ? 0 : 300;
  const total = subtotal + delivery;
  const submit = (event) => { event.preventDefault(); setComplete(true); onComplete(); };
  if (complete) return <div className="checkout-view"><div className="text-center py-5"><i className="bi bi-check-circle-fill display-3 text-success" /><h2 className="h3 mt-3">Order request received</h2><p className="text-secondary">This demo does not process payments. A customer-care flow can be connected here later.</p><button className="btn btn-dark" onClick={onClose}>Continue shopping</button></div></div>;
  return <div className="checkout-view"><div className="d-flex justify-content-between align-items-center mb-4"><div><p className="eyebrow mb-1"><span /> Checkout</p><h2 className="h3 mb-0">Ready when you are.</h2></div><button className="btn-close" onClick={onClose} aria-label="Close checkout" /></div><form onSubmit={submit}><div className="row g-3"><div className="col-12"><label className="form-label" htmlFor="customer-name">Full name</label><input id="customer-name" className="form-control" required placeholder="Linet Wairimu" /></div><div className="col-md-6"><label className="form-label" htmlFor="customer-phone">Phone</label><input id="customer-phone" className="form-control" required placeholder="0715 808 885" /></div><div className="col-md-6"><label className="form-label" htmlFor="customer-email">Email</label><input id="customer-email" type="email" className="form-control" required placeholder="you@example.com" /></div><div className="col-12"><label className="form-label" htmlFor="delivery-location">Delivery location</label><input id="delivery-location" className="form-control" required placeholder="Town / estate / landmark" /></div><div className="col-12"><span className="form-label d-block">Payment option</span><div className="d-flex flex-column gap-2"><label className="payment-option"><input type="radio" name="payment" checked={payment === 'mpesa'} onChange={() => setPayment('mpesa')} /> <span><strong>M-Pesa</strong><small> Pay securely via mobile money</small></span></label><label className="payment-option"><input type="radio" name="payment" checked={payment === 'cash'} onChange={() => setPayment('cash')} /> <span><strong>Cash on Delivery</strong><small> Pay when your order arrives</small></span></label></div></div></div><div className="order-summary mt-4"><h3 className="h6">Order summary</h3>{cart.map((item) => <div className="d-flex justify-content-between small py-1" key={item.name}><span>{item.name} × {item.quantity}</span><span>{money(item.price * item.quantity)}</span></div>)}<hr /><div className="d-flex justify-content-between small"><span>Delivery</span><span>{delivery ? money(delivery) : 'Free'}</span></div><div className="d-flex justify-content-between mt-2"><strong>Total</strong><strong>{money(total)}</strong></div></div><button className="btn btn-warning w-100 mt-4" type="submit">Place demo order <i className="bi bi-arrow-right ms-2" /></button></form></div>;
}
